### ISSUE TITLE
Failed to load PeftModel with a pretrained LLM and a trained qlora

### ISSUE THREAD

**Issue by NgoDoanKien** [huggingface/peft#1096] opened 2023-11-08 12:15 UTC
### System Info

All imported ones are latest

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

CODE

```
model_name = "vilm/vietcuna-7b-v3"
PeftModel.from_pretrained(vi_model_merge, 'kienlc1/vietcuna-7b-test')
```

ERROR:

```
AttributeError                            Traceback (most recent call last)

Cell In[9], line 2
      1 device_map={'': 0}
----> 2 vi_model_final = PeftModel.from_pretrained(vi_model_merge, 'kienlc1/vietcuna-7b-test', device_map={'':0})
      3 vi_model_final = vi_model_final.merge_and_unload()
      4 vi_model_final.eval()

File /opt/conda/lib/python3.10/site-packages/peft/peft_model.py:306, in PeftModel.from_pretrained(cls, model, model_id, adapter_name, is_trainable, config, **kwargs)
    304 else:
    305     model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
--> 306 model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
    307 return model

File /opt/conda/lib/python3.10/site-packages/peft/peft_model.py:606, in PeftModel.load_adapter(self, model_id, adapter_name, is_trainable, **kwargs)
    603 adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
    605 # load the weights into the model
--> 606 load_result = set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
    607 if (
    608     (getattr(self, "hf_device_map", None) is not None)
    609     and (len(set(self.hf_device_map.values()).intersection({"cpu", "disk"})) > 0)
    610     and len(self.peft_config) == 1
    611 ):
    612     device_map = kwargs.get("device_map", "auto")

File /opt/conda/lib/python3.10/site-packages/peft/utils/save_and_load.py:158, in set_peft_model_state_dict(model, peft_model_state_dict, adapter_name)
    155 else:
    156     raise NotImplementedError
--> 158 load_result = model.load_state_dict(peft_model_state_dict, strict=False)
    159 if config.is_prompt_learning:
    160     model.prompt_encoder[adapter_name].embedding.load_state_dict(
    161         {"weight": peft_model_state_dict["prompt_embeddings"]}, strict=True
    162     )

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:2027, in Module.load_state_dict(self, state_dict, strict)
   2020         out = hook(module, incompatible_keys)
   2021         assert out is None, (
   2022             "Hooks registered with ``register_load_state_dict_post_hook`` are not"
   2023             "expected to return new values, if incompatible_keys need to be modified,"
   2024             "it should be done inplace."
   2025         )
-> 2027 load(self, state_dict)
   2028 del load
   2030 if strict:

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:2015, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2013         child_prefix = prefix + name + '.'
   2014         child_state_dict = {k: v for k, v in local_state_dict.items() if k.startswith(child_prefix)}
-> 2015         load(child, child_state_dict, child_prefix)
   2017 # Note that the hook can modify missing_keys and unexpected_keys.
   2018 incompatible_keys = _IncompatibleKeys(missing_keys, unexpected_keys)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:2015, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2013         child_prefix = prefix + name + '.'
   2014         child_state_dict = {k: v for k, v in local_state_dict.items() if k.startswith(child_prefix)}
-> 2015         load(child, child_state_dict, child_prefix)
   2017 # Note that the hook can modify missing_keys and unexpected_keys.
   2018 incompatible_keys = _IncompatibleKeys(missing_keys, unexpected_keys)

    [... skipping similar frames: Module.load_state_dict.<locals>.load at line 2015 (5 times)]

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:2015, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2013         child_prefix = prefix + name + '.'
   2014         child_state_dict = {k: v for k, v in local_state_dict.items() if k.startswith(child_prefix)}
-> 2015         load(child, child_state_dict, child_prefix)
   2017 # Note that the hook can modify missing_keys and unexpected_keys.
   2018 incompatible_keys = _IncompatibleKeys(missing_keys, unexpected_keys)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:2009, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2007 def load(module, local_state_dict, prefix=''):
   2008     local_metadata = {} if metadata is None else metadata.get(prefix[:-1], {})
-> 2009     module._load_from_state_dict(
   2010         local_state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
   2011     for name, child in module._modules.items():
   2012         if child is not None:

File /opt/conda/lib/python3.10/site-packages/bitsandbytes/nn/modules.py:254, in Linear4bit._load_from_state_dict(self, state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
    252 if self.bias is not None:
    253     bias_data = state_dict.pop(prefix + "bias", None)
--> 254     self.bias.data = bias_data.to(self.bias.data.device)
    256 self.weight, state_dict = bnb.nn.Params4bit.from_state_dict(
    257                 state_dict, prefix=prefix + "weight" + ".", requires_grad=False
    258             )
    259 unexpected_keys.extend(state_dict.keys())

AttributeError: 'NoneType' object has no attribute 'to'
```

### Expected behavior

The codes were executed successfully yesterday but failed today. I tried downgrading bitsandbytes==0.41.1 and everything worked well.

**Comment by BenjaminBossan** [comment] 2023-11-08 12:25
Looks like a duplicate of #1095.

**Closed** 2023-12-17 15:03 UTC
