### ISSUE TITLE
Error while working with custom model in trainer

### ISSUE THREAD

**Issue by funger1990** [huggingface/peft#1197] opened 2023-11-30 04:07 UTC
### System Info

python=3.8.16
torch=1.13.0+cu117
transformers=4.33.2
peft=0.6.2
accelerate=0.23.0

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [x] My own task or dataset (give details below)

### Reproduction

Minimal test case
**AttributeError: 'dict' object has no attribute 'to_json_string'**

```
import torch
import datasets
import transformers
import peft


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(10, 10)

    def __call__(self, input, labels):
        return {
            'loss': torch.tensor(1.0, requires_grad=True)
            }

model = Model()

peft_config = peft.LoraConfig(target_modules=['linear'])
model = peft.get_peft_model(model, peft_config)


ds = datasets.Dataset.from_list([
    {'input': [1, 2], 'label': -1},
    {'input': [1, 2], 'label': -1}
])

training_args = transformers.TrainingArguments(
    output_dir='../tmp/',
    logging_dir='../tmp/',
    max_steps=20)

trainer = transformers.Trainer(
    args=training_args,
    model=model,
    train_dataset=ds,
    eval_dataset=ds)

trainer.train()
```

### Expected behavior

trainer.train() works

**Comment by BenjaminBossan** [comment] 2023-11-30 10:07
Thanks for reporting the error and providing the code snippet. I could not reproduce the error, instead I get:

> TypeError: Model.__call__() missing 1 required positional argument: 'input'

as the arguments to `forward` only contain `labels`. What version of PEFT/transformers/accelerate are you using?

Also, could you please show the whole stacktrace?

**Comment by funger1990** [comment] 2023-11-30 10:34
package version
```
python=3.8.16
torch=1.13.0+cu117
transformers=4.33.2
peft=0.6.2
accelerate=0.23.0
```

whole stack trace
```
AttributeError                            Traceback (most recent call last)
/ml-vepfs/workspace/zhangf/code/test.ipynb Cell 2 line 3
     28 training_args = transformers.TrainingArguments(
     29     output_dir='../tmp/',
     30     logging_dir='../tmp/',
     31     max_steps=20)
     33 trainer = transformers.Trainer(
     34     args=training_args,
     35     model=model,
     36     train_dataset=ds,
     37     eval_dataset=ds)
---> 39 trainer.train()

File ~/miniconda3/lib/python3.8/site-packages/transformers/trainer.py:1553, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1551         hf_hub_utils.enable_progress_bars()
   1552 else:
-> 1553     return inner_training_loop(
   1554         args=args,
   1555         resume_from_checkpoint=resume_from_checkpoint,
   1556         trial=trial,
   1557         ignore_keys_for_eval=ignore_keys_for_eval,
   1558     )

File ~/miniconda3/lib/python3.8/site-packages/transformers/trainer.py:1778, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1775 self._globalstep_last_logged = self.state.global_step
   1776 model.zero_grad()
-> 1778 self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
   1780 # Skip the first epochs_trained epochs to get the random state of the dataloader at the right point.
   1781 if not args.ignore_data_skip:

File ~/miniconda3/lib/python3.8/site-packages/transformers/trainer_callback.py:362, in CallbackHandler.on_train_begin(self, args, state, control)
    360 def on_train_begin(self, args: TrainingArguments, state: TrainerState, control: TrainerControl):
    361     control.should_training_stop = False
--> 362     return self.call_event("on_train_begin", args, state, control)

File ~/miniconda3/lib/python3.8/site-packages/transformers/trainer_callback.py:406, in CallbackHandler.call_event(self, event, args, state, control, **kwargs)
    404 def call_event(self, event, args, state, control, **kwargs):
    405     for callback in self.callbacks:
--> 406         result = getattr(callback, event)(
    407             args,
    408             state,
    409             control,
    410             model=self.model,
    411             tokenizer=self.tokenizer,
    412             optimizer=self.optimizer,
    413             lr_scheduler=self.lr_scheduler,
    414             train_dataloader=self.train_dataloader,
    415             eval_dataloader=self.eval_dataloader,
    416             **kwargs,
    417         )
    418         # A Callback can skip the return of `control` if it doesn't change it.
    419         if result is not None:

File ~/miniconda3/lib/python3.8/site-packages/transformers/integrations/integration_utils.py:629, in TensorBoardCallback.on_train_begin(self, args, state, control, **kwargs)
    627 model = kwargs["model"]
    628 if hasattr(model, "config") and model.config is not None:
--> 629     model_config_json = model.config.to_json_string()
    630     self.tb_writer.add_text("model_config", model_config_json)

AttributeError: 'dict' object has no attribute 'to_json_string'
```

**Comment by funger1990** [comment] 2023-11-30 10:41
If I use `peft.inject_adapter_in_model` instead of `peft.get_peft_model`, then it works without bugs.
```
import torch
import datasets
import transformers
import peft


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(10, 10)

    def __call__(self, input, labels):
        return {
            'loss': torch.tensor(1.0, requires_grad=True)
            }

model = Model()

peft_config = peft.LoraConfig(target_modules=['linear'])

# use peft.inject_adapter_in_model instead of peft.get_peft_model
model = peft.inject_adapter_in_model(peft_config, model)

ds = datasets.Dataset.from_list([
    {'input': [1, 2], 'label': -1},
    {'input': [1, 2], 'label': -1}
])

training_args = transformers.TrainingArguments(
    output_dir='../tmp/',
    logging_dir='../tmp/',
    max_steps=20)

trainer = transformers.Trainer(
    args=training_args,
    model=model,
    train_dataset=ds,
    eval_dataset=ds)

trainer.train()
```

**Comment by BenjaminBossan** [comment] 2023-11-30 11:09
I see, thanks for giving more context.

So what appears to be happening here is that since custom models don't normally have a `config` attribute (which is required in a few places), PEFT sets the attribute automatically to the dict `{"model_type": "custom"}`. When you check `model.config` after you call `get_peft_model`, you'll see that attribute.

Now transformers `Trainer` checks if the config attribute is present and if it is, assumes that it must be a `transformers.PretrainedConfig`, which has the `to_json_string` method, resulting in the error. When you call `inject_adapter_in_model`, there will be no `config` attribute, so `Trainer` doesn't try to call the method.

If this works for your use case, then it should be fine, but note that with `inject_adapter_in_model`, you get back a normal PyTorch `nn.Module`, not a `PeftModel`, so you lose access to some utility methods like merging the adapter weights. If you don't need those, you'll be fine.

Otherwise, what you could try is to use `get_peft_model` as in the first example, but after calling it, you delete the `model.config` attribute or you replace it by a `transformers.PretrainedConfig`. Meanwhile, I'll check if we can do something in PEFT to improve the situation.

**Comment by BenjaminBossan** [comment] 2024-01-02 10:02
Btw we no longer set a `config` attribute on custom models (via #1200), so this should be fixed now.

**Closed by BenjaminBossan** 2024-01-02 10:02 UTC
