### ISSUE TITLE
pissa error: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by zhihao-chen** [huggingface/peft#1912] opened 2024-07-08 06:22 UTC
Why did I get this error when I used the pissa method to fine-tune qwen2-7b-instruct:

```
model = get_peft_model(model, config)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/mapping.py", line 149, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/peft_model.py", line 1395, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/peft_model.py", line 138, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/lora/model.py", line 139, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 166, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 372, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/lora/model.py", line 223, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/lora/model.py", line 314, in _create_new_module
    new_module = dispatcher(target, adapter_name, lora_config=lora_config, **kwargs)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/lora/layer.py", line 1116, in dispatch_default
    new_module = Linear(target, adapter_name, **kwargs)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/lora/layer.py", line 410, in __init__
    self.update_layer(
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/lora/layer.py", line 117, in update_layer
    self.pissa_init(adapter_name, init_lora_weights)
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/tuners/lora/layer.py", line 179, in pissa_init
    Vr, Sr, Ur = svd_lowrank(
  File "/usr/local/lib/python3.9/dist-packages/torch/_lowrank.py", line 137, in svd_lowrank
    return _svd_lowrank(A, q=q, niter=niter, M=M)
  File "/usr/local/lib/python3.9/dist-packages/torch/_lowrank.py", line 147, in _svd_lowrank
    m, n = A.shape[-2:]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by BenjaminBossan** [comment] 2024-07-08 09:01
It's not possible to tell just from the error message you showed. Ideally, you could share the code to reproduce the error, at the very least it would help to know which model you used and which `LoraConfig`.

**Comment by zhihao-chen** [comment] 2024-07-08 09:32
Experimental environment and model loading method:
- GPU: 2*A800
- base model:Qwen2-7B-Instruct
- deepspeed zero3
- bf16
- lora_config:
{
    "lora_r": 64,
    "lora_alpha": 128,
    "lora_dropout": 0.05,
    "lora_target_modules": [
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "up_proj",
        "gate_proj",
        "down_proj"
    ]
}
- max_lens:3400

model = AutoModelForCausalLM.from_pretrained(
            model_args.model_name_or_path,
            device_map=device_map,
            max_memory=max_memory,
            trust_remote_code=True,
            resume_download=True,
            quantization_config=None,
            low_cpu_mem_usage=False
        )
config = LoraConfig(
                    r=lora_config['lora_r'],
                    lora_alpha=lora_config['lora_alpha'],
                    target_modules=modules,
                    lora_dropout=lora_config['lora_dropout'],
                    bias="none",
                    task_type=TaskType.CAUSAL_LM,
                    init_lora_weights="pissa_niter_4"
                )
model = get_peft_model(model, config)

**Comment by BenjaminBossan** [comment] 2024-07-08 09:51
The `LoraConfig` looks correct so far. Could you please tell me what the base model is?

**Comment by zhihao-chen** [comment] 2024-07-08 09:53
Qwen2-7B-Instruct

**Comment by BenjaminBossan** [comment] 2024-07-08 10:12
Thanks for the info. I could not reproduce the error :( Could you try if this script works for you?

```python
import torch
from peft import LoraConfig, get_peft_model, PeftModel, TaskType
from transformers import AutoModelForCausalLM

model_id = "Qwen/Qwen2-7B-Instruct"
model = AutoModelForCausalLM.from_pretrained(model_id)
target_modules = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "up_proj",
    "gate_proj",
    "down_proj",
]

config = LoraConfig(
    r=64, lora_alpha=128, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM", init_lora_weights="pissa_niter_4", target_modules=target_modules
)
peft_model = get_peft_model(model, config)
```

I also tried on GPU but had to lower the dtype to fit it in memory:

`model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16, device_map=0)`

If this passes for you too, it means that something must be different in your script. If you get an error, it could be a version issue, in which case it would be helpful to know the versions of PEFT, torch, transformers, accelerate.

**Comment by BenjaminBossan** [comment] 2024-07-08 10:20
What PEFT version are you using? Could you try to install from the latest `main` branch, I think this could be solved now.

**Comment by zhihao-chen** [comment] 2024-07-08 11:08
peft=0.11.1

I found a phenomenon that using deepspeed zero2 will not report an error, but zero3 will report the above error。Do you know what the reason is?

**Comment by zhihao-chen** [comment] 2024-07-08 11:33
Thanks, I will try.

**Comment by zhihao-chen** [comment] 2024-07-09 03:25
You are right. The latest PEFT version can solve the problem.

**Comment by BenjaminBossan** [comment] 2024-07-09 08:38
Fantastic, this supports my hypothesis on what went wrong. I'll close this issue then, fee free to re-open if something new comes up.

**Closed by BenjaminBossan** 2024-07-09 08:38 UTC
