### ISSUE TITLE
model.load_adapter Problem

### ISSUE THREAD

**Issue by syngokhan** [huggingface/peft#276] opened 2023-04-07 12:24 UTC
Hello, today after downloading and installing PEFT again, I am getting the following line. But I was not getting such an error before. And my code was working. It's not working now.

I had created the requirement.txt file before. There is this in the peft version created here, maybe it can help.
peft @ git+https://github.com/huggingface/peft.git@64f63a7df2a02cfd144592d9aa9c871b59258c55

>>> Python 3.7.7
-----
>>> transformers.__version__
'4.21.3'
>>> torch.__version__
'1.9.1+cu111'

```
/home/glb90092345/DialoGPT/API/api.py:46 in <module>                                             │
│                                                                                                  │
│    43 │   #device = "cpu",                                                                       │
│    44 │   info = False                                                                           │
│    45 )                                                                                          │
│ ❱  46 test.load()                                                                                │
│    47                                                                                            │
│    48 app = FastAPI()                                                                            │
│    49                                                                                            │
│                                                                                                  │
│ /home/glb90092345/DialoGPT/API/model.py:198 in load                                              │
│                                                                                                  │
│   195 │   │   │   │   )                                                                          │
│   196 │   │   │                                                                                  │
│   197 │   │   │   # Load the Lora model                                                          │
│ ❱ 198 │   │   │   self.model = PeftModel.from_pretrained(self.model.to(self.device), self.mode   │
│   199                                                                                            │
│   200                                                                                            │
│   201                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.7/site-packages/peft/peft_model.py:166 in from_pretrained                 │
│                                                                                                  │
│    163 │   │   │   model = cls(model, config, adapter_name)                                      │
│    164 │   │   else:                                                                             │
│    165 │   │   │   model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, ad  │
│ ❱  166 │   │   model.load_adapter(model_id, adapter_name, **kwargs)                              │
│    167 │   │   return model                                                                      │
│    168 │                                                                                         │
│    169 │   def _setup_prompt_encoder(self, adapter_name):                                        │
│                                                                                                  │
│ /usr/local/lib/python3.7/site-packages/peft/peft_model.py:355 in load_adapter                    │
│                                                                                                  │
│    352 │   │   │   filename, map_location=torch.device("cuda" if torch.cuda.is_available() else  │
│    353 │   │   )                                                                                 │
│    354 │   │   # load the weights into the model                                                 │
│ ❱  355 │   │   set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)      │
│    356 │   │   if (                                                                              │
│    357 │   │   │   (getattr(self, "hf_device_map", None) is not None)                            │
│    358 │   │   │   and (len(set(self.hf_device_map.values()).intersection({"cpu", "disk"})) > 0  │
│                                                                                                  │
│ /usr/local/lib/python3.7/site-packages/peft/utils/save_and_load.py:120 in                        │
│ set_peft_model_state_dict                                                                        │
│                                                                                                  │
│   117 │   else:                                                                                  │
│   118 │   │   raise NotImplementedError                                                          │
│   119 │                                                                                          │
│ ❱ 120 │   model.load_state_dict(peft_model_state_dict, strict=False)                             │
│   121 │   if isinstance(config, PromptLearningConfig):                                           │
│   122 │   │   model.prompt_encoder[adapter_name].embedding.load_state_dict(                      │
│   123 │   │   │   {"weight": peft_model_state_dict["prompt_embeddings"]}, strict=True            │
│                                                                                                  │
│ /usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py:1407 in load_state_dict        │
│                                                                                                  │
│   1404 │   │                                                                                     │
│   1405 │   │   if len(error_msgs) > 0:                                                           │
│   1406 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(     │
│ ❱ 1407 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))         │
│   1408 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)                           │
│   1409 │                                                                                         │
│   1410 │   def _named_members(self, get_members_fn, prefix='', recurse=True):  


RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.transformer.h.0.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.0.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.1.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.1.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.2.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.2.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.3.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.3.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.4.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.4.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.5.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.5.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.6.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.6.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.7.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.7.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.8.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.8.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.9.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.9.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.10.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.10.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.11.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.11.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.12.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.12.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.13.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.13.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.14.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.14.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.15.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.15.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.16.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.16.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.17.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.17.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.18.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.18.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.19.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.19.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.20.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.20.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.21.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.21.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.22.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.22.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).
        size mismatch for base_model.model.transformer.h.23.attn.c_attn.lora_A.default.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in
current model is torch.Size([16, 1024]).
        size mismatch for base_model.model.transformer.h.23.attn.c_attn.lora_B.default.weight: copying a param with shape torch.Size([2048, 16, 1]) from checkpoint, the shape
in current model is torch.Size([3072, 16]).

**Comment by pacman100** [comment] 2023-04-07 12:57
Hello @syngokhan, as explained in the latest PR https://github.com/huggingface/peft/pull/263#issuecomment-1497338967, the breaking change is for the models that used MergedLinear layers in LoRA as the support for it was supported, the reasons outlined in the link shared.  So, models impacted are GPT-2, Bloom variants as they will now use the same LoRA Linear layers as all the others.

**Comment by raihan0824** [comment] 2023-04-14 05:35
Hi, I got the same problem. How to fix it?

**Comment by pacman100** [comment] 2023-04-14 06:43
Hello, as this is a breaking change, currently the way is to retrain the model

**Comment by syngokhan** [comment] 2023-04-14 17:29
> Hi, I got the same problem. How to fix it?

if you train the model again the problem is solved

**Comment by SefaZeng** [comment] 2023-05-09 02:54
I retrained my model, but the problem is still here.

**Comment by syngokhan** [comment] 2023-05-10 09:43
> I retrained my model, but the problem is still here.

Can you upgrade peft library ? And then train model ? And share problem

**Closed** 2023-06-11 15:03 UTC
