### ISSUE TITLE
TypeError: dispatch_model() got an unexpected keyword argument 'offload_index'

### ISSUE THREAD

**Issue by imrankh46** [huggingface/peft#186] opened 2023-03-18 10:53 UTC
================================

ruuning the following code on kaggle notebook give me this error
================================

`import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"
import torch
import torch.nn as nn
import bitsandbytes as bnb
from transformers import AutoTokenizer, AutoConfig, AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    "bigscience/bloom-7b1", 
    load_in_8bit=True, 
    device_map='auto',
)

tokenizer = AutoTokenizer.from_pretrained("bigscience/bloom-7b1")`

======================================

 on kaggle notebook give me the this error

======================================

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_40247/570955428.py in <module>
      9     "bigscience/bloom-7b1",
     10     load_in_8bit=True,
---> 11     device_map='auto',
     12 )
     13 

/opt/conda/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    470             model_class = _get_model_class(config, cls._model_mapping)
    471             return model_class.from_pretrained(
--> 472                 pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    473             )
    474         raise ValueError(

/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   2695         # Dispatch model with hooks on all devices if necessary
   2696         if device_map is not None:
-> 2697             dispatch_model(model, device_map=device_map, offload_dir=offload_folder, offload_index=offload_index)
   2698 
   2699         if output_loading_info:

TypeError: dispatch_model() got an unexpected keyword argument 'offload_index'`

**Comment by aravindveluri** [comment] 2023-03-18 21:47
+1, got the same error when running alpaca lora

**Comment by imrankh46** [comment] 2023-03-19 03:50
> +1, got the same error when running alpaca lora

Why they give me this error. The same code is working on colab but not kaggle notebook.

**Comment by Beyondo** [comment] 2023-03-19 09:50
+1 It used to work on Kaggle, I literally changed nothing about the env, and suddenly I discovered it broke today.

**Comment by imrankh46** [comment] 2023-03-19 09:56
> +1 It used to work on Kaggle, I literally changed nothing about the env, and suddenly I discovered it broke today.

So the solution is ? Leave it

**Comment by Beyondo** [comment] 2023-03-19 10:00
> > +1 It used to work on Kaggle, I literally changed nothing about the env, and suddenly I discovered it broke today.
> 
> So the solution is ? Leave it

There's no solution. A workaround is just don't use `device_map="auto"` till they fix it I guess 🤷

**Comment by imrankh46** [comment] 2023-03-19 10:03
> 

The `device_map="auto"` why not working with my code.

**Comment by imrankh46** [comment] 2023-03-19 10:03
> > > +1 It used to work on Kaggle, I literally changed nothing about the env, and suddenly I discovered it broke today.
> > 
> > 
> > So the solution is ? Leave it
> 
> There's no solution. A workaround is just don't use `device_map="auto"` till they fix it I guess 🤷

I ask another question please give me response

**Comment by imrankh46** [comment] 2023-03-19 10:04
> > > +1 It used to work on Kaggle, I literally changed nothing about the env, and suddenly I discovered it broke today.
> > 
> > 
> > So the solution is ? Leave it
> 
> There's no solution. A workaround is just don't use `device_map="auto"` till they fix it I guess 🤷

I mean I create another issues. Want to use pytorch 2 for faster training getting some bad error

**Comment by younesbelkada** [comment] 2023-03-20 08:54
Hi
Can you try to upgrade `accelerate` ?
`pip install --upgrade accelerate`

**Comment by imrankh46** [comment] 2023-03-20 08:56
> Hi Can you try to upgrade `accelerate` ? `pip install --upgrade accelerate`

When I installing these packages it give me warning. I will shere the warning in while.

**Comment by imrankh46** [comment] 2023-03-20 09:01
> 

![Screenshot_20230320-140011](https://user-images.githubusercontent.com/103720343/226292542-5d17e4be-e859-4429-9ed3-44a8266f162d.png)
They give me warning ⚠️

**Comment by imrankh46** [comment] 2023-03-20 09:03
> Hi Can you try to upgrade `accelerate` ? `pip install --upgrade accelerate`

Can you shere the working installation solution for kaggle 
Like 

```
!pip install transformers Datasets
!pip install accelerate lora 
Etc 
```

**Comment by rasmi** [comment] 2023-04-01 12:22
@imrankh46 -- the issue is that your `accelerate` version is out of date. As @younesbelkada suggested, try something like:
```
!pip install -U transformers
!pip install -U accelerate
```

**Comment by Patrick-Ni** [comment] 2023-04-10 07:04
> Hi Can you try to upgrade `accelerate` ? `pip install --upgrade accelerate`

that works for me, thank you!

**Comment by younesbelkada** [comment] 2023-04-10 08:26
Thanks! Feel free to close the issue

**Closed** 2023-05-04 15:04 UTC

**Comment by TheFaheem** [comment] 2023-05-17 03:39
Even After Upgrading, It Shows the same error

**Comment by younesbelkada** [comment] 2023-06-09 14:00
Hi @vrunm 
Can you share a reproducible script?

**Comment by imrankh46** [comment] 2023-06-09 14:03
> @TheFaheem I agree with you ran into the same issue.

First disconnect the run time. 
And then install the following library. 


```
!pip install -q -U transformers datasets
!pip install -q -U accelerate

```

**Comment by TheFaheem** [comment] 2023-06-09 14:06
Not the Package Problem. Kaggle NB Sucks!

Just Restart the kernel and run the package update lines first. It Should be Work fine.

**Comment by younesbelkada** [comment] 2023-06-09 14:10
Awesome thanks for confirming!

**Comment by vrunm** [comment] 2023-06-09 14:46
@TheFaheem Thanks I got it to work in a kaggle notebook.

**Comment by eguar11011** [comment] 2023-06-30 04:51
> Even After Upgrading, It Shows the same error

@TheFaheem 
I install these first packages:
```
!pip install -U -q transformers bitsandbytes accelerate loralib
!pip install -q git+https://github.com/huggingface/peft.git
!pip install accelerate==0.18.0
```
and then run the model. And then if I install any other package because if I install other related packages I still get the same error.

**Comment by eguar11011** [comment] 2023-06-30 05:33
I install these first packages: 
```
!pip install -U -q transformers bitsandbytes accelerate loralib
!pip install -q git+https://github.com/huggingface/peft.git
!pip install accelerate==0.18.0
```
and then I run the model. And then if I install any other package because if I install other related packages I still get the same error.

For example if I install first:
```
! pip install langchain
! pip install annoy
! pip install sentence_transformers
```
and then the model packages. I get the error.
