### ISSUE TITLE
'Linear4bit' object has no attribute 'compute_dtype'

### ISSUE THREAD

**Issue by d1pankarmedhi** [huggingface/peft#1209] opened 2023-12-04 17:48 UTC
### System Info

**Instance**: T4 (Colab)
Occured while running the example notebook `bnb-4bit-training-with-inference.ipynb` forQLora training.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Error occured while running the notebook `bnb-4bit-training-with-inference.ipynb` on free T4 colab instance.

```python
lora_config = LoraConfig.from_pretrained('outputs')
peft_model = get_peft_model(model, lora_config)
```

```bash
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-30f3e82a4451>](https://localhost:8080/#) in <cell line: 2>()
      1 lora_config = LoraConfig.from_pretrained('outputs')
----> 2 peft_model = get_peft_model(model, lora_config)

8 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1693             if name in modules:
   1694                 return modules[name]
-> 1695         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
   1696 
   1697     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'Linear4bit' object has no attribute 'compute_dtype'
```

### Expected behavior

the model successfully loaded.

**Comment by younesbelkada** [comment] 2023-12-05 16:28
Hi @d1pankarmedhi 
Thanks for the issue, can you paste the full traceback of the error? Also how do you load the base model?
Can you also try to run that script with the latest version of `bitsandbytes` ? `pip install -U bitsandbytes`

**Comment by daptheHuman** [comment] 2023-12-06 14:45
> Hi @d1pankarmedhi Thanks for the issue, can you paste the full traceback of the error? Also how do you load the base model? Can you also try to run that script with the latest version of `bitsandbytes` ? `pip install -U bitsandbytes`

same issue here, bitsandbytes 0.41.2.post2

**Comment by younesbelkada** [comment] 2023-12-06 15:23
Can you share a full reproducer of the issue? ideally with a small snippet

**Comment by abishek-ctrl** [comment] 2023-12-07 06:10
Been having the same issue.

The complete traceback for the code.
```
`AttributeError                            Traceback (most recent call last)
[<ipython-input-10-fba3e7b63116>](https://localhost:8080/#) in <cell line: 2>()
      1 lora_config = LoraConfig.from_pretrained('outputs')
----> 2 model = get_peft_model(model, lora_config)

8 frames
[/usr/local/lib/python3.10/dist-packages/peft/mapping.py](https://localhost:8080/#) in get_peft_model(model, peft_config, adapter_name, mixed)
    131     if peft_config.is_prompt_learning:
    132         peft_config = _prepare_prompt_learning_config(peft_config, model_config)
--> 133     return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
    134 
    135 

[/usr/local/lib/python3.10/dist-packages/peft/peft_model.py](https://localhost:8080/#) in __init__(self, model, peft_config, adapter_name)
   1039 
   1040     def __init__(self, model: torch.nn.Module, peft_config: PeftConfig, adapter_name: str = "default") -> None:
-> 1041         super().__init__(model, peft_config, adapter_name)
   1042         self.base_model_prepare_inputs_for_generation = self.base_model.prepare_inputs_for_generation
   1043 

[/usr/local/lib/python3.10/dist-packages/peft/peft_model.py](https://localhost:8080/#) in __init__(self, model, peft_config, adapter_name)
    121             self._peft_config = None
    122             cls = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type]
--> 123             self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
    124             self.set_additional_trainable_modules(peft_config, adapter_name)
    125 

[/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py](https://localhost:8080/#) in __init__(self, model, config, adapter_name)
    117 
    118     def __init__(self, model, config, adapter_name) -> None:
--> 119         super().__init__(model, config, adapter_name)
    120 
    121     def _check_new_adapter_config(self, config: LoraConfig) -> None:

[/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py](https://localhost:8080/#) in __init__(self, model, peft_config, adapter_name)
     93             self.config = {"model_type": "custom"}
     94 
---> 95         self.inject_adapter(self.model, adapter_name)
     96 
     97         # Copy the peft_config in the injected model.

[/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py](https://localhost:8080/#) in inject_adapter(self, model, adapter_name)
    250                 "current_key": key,
    251             }
--> 252             self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
    253 
    254         if not is_target_modules_in_base_model:

[/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py](https://localhost:8080/#) in _create_and_replace(self, lora_config, adapter_name, target, target_name, parent, current_key, **optional_kwargs)
    198             )
    199         else:
--> 200             new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
    201             if adapter_name != self.active_adapter:
    202                 # adding an additional adapter: it is not automatically trainable

[/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py](https://localhost:8080/#) in _create_new_module(lora_config, adapter_name, target, **kwargs)
    284             fourbit_kwargs.update(
    285                 {
--> 286                     "compute_dtype": target.compute_dtype,
    287                     "compress_statistics": target.weight.compress_statistics,
    288                     "quant_type": target.weight.quant_type,

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1693             if name in modules:
   1694                 return modules[name]
-> 1695         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
   1696 
   1697     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'Linear4bit' object has no attribute 'compute_dtype'
```

**Comment by alvations** [comment] 2023-12-07 07:27
This is an issue where the bnb dependency upstream. Try doing this as a interim solution until a new `bitsandbytes>0.41.3`

```
! pip install git+https://github.com/TimDettmers/bitsandbytes.git
```

Here's a working example https://colab.research.google.com/drive/1u22vX37cCYNKjtI9bkgz-LmaqEVjVOJv?usp=sharing

**Comment by younesbelkada** [comment] 2023-12-07 08:19
Hi everyone, 
bnb recently release the 0.41.3 version which should fix the bug, can you try:
```bash
pip install -U bitsandbytes
```
cc @Titus-von-Koeller 
In case this does not fix your issue, can you try to reproduce the issue with a small snippet, e.g. the script below:
```python
from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model

model_id = "facebook/opt-350m"
model = AutoModelForCausalLM.from_pretrained(model_id, load_in_4bit=True)

lora_config = LoraConfig(
    r=8,
    peft_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
```
Works fine for me

**Comment by Titus-von-Koeller** [comment] 2023-12-07 09:24
Yeah, I could verify with [bnb-4bit-training-with-inference.ipynb - Colab](https://colab.research.google.com/drive/1Vvju5kOyBsDr7RX_YAvp6ZsSOoSMjhKD?usp=sharing), as provided by @d1pankarmedhi in his issue description, that:

- `bitsandbytes 0.41.2.post2` reproduces the bug
- `bitsandbytes==0.41.3` fixes the bug

This was likely caused by @poedator 's recent 4-bit serialization refactor for which we just merged and released his recent follow-up PR, which seems to fix this.

Thanks everyone for raising this and thanks @poedator for the useful refactor.

**Comment by pod2c** [comment] 2023-12-09 03:49
> Yeah, I could verify with [bnb-4bit-training-with-inference.ipynb - Colab](https://colab.research.google.com/drive/1Vvju5kOyBsDr7RX_YAvp6ZsSOoSMjhKD?usp=sharing), as provided by @d1pankarmedhi in his issue description, that:
> 
> * `bitsandbytes 0.41.2.post2` reproduces the bug
> * `bitsandbytes==0.41.3` fixes the bug
> 
> This was likely caused by @poedator 's recent 4-bit serialization refactor for which we just merged and released his recent follow-up PR, which seems to fix this.
> 
> Thanks everyone for raising this and thanks @poedator for the useful refactor.

Hi, I upgraded to bitsandbyte 0.41.3 but my code still cannot work, the error was the same "'Linear4bit' object has no attribute 'compute_dtype'", I have tried restart kernel, uninstall and install but all failed.
<img width="548" alt="屏幕截图 2023-12-09 114918" src="https://github.com/huggingface/peft/assets/52070996/427e381d-0d39-4d7c-8209-8231da376d8b">

**Comment by poedator** [comment] 2023-12-09 21:08
Hi, @pod2c, thank you for testing!
I tried to run your example in Colab, but it went OOM.  
So I went with a smaller model `mrsteyk/openchatgpt-neox-125m` and was able to reproduce the error. 
https://colab.research.google.com/drive/1Pu190aLnw9WHkGgfjdPsMIFgq0FU9fv5

Then I tested it locally on A100 with bnb==0.41.3 and observed no error. 

Let me try to figure out what goes wring in Colab. Suggestions welcome.

**Comment by pod2c** [comment] 2023-12-10 04:17
> Hi, @pod2c, thank you for testing! I tried to run your example in Colab, but it went OOM. So I went with a smaller model `mrsteyk/openchatgpt-neox-125m` and was able to reproduce the error. https://colab.research.google.com/drive/1Pu190aLnw9WHkGgfjdPsMIFgq0FU9fv5
> 
> I tested the packages versions and it appears that the error happens with `peft==0.7.0` It was not happening with `peft==0.6.2 and 0.6.0`
> 
> Then I tested older bnb releases and found that the error still happens with `bitsandbytes==0.40.2` and `0.41.1`. So this issue seems to be related not to my recent quantization PRs but rather to something on PEFT side. @Titus-von-Koeller what do you think?

Hi, thank you for helping! I have tried peft 0.6.2 and it worked.

**Comment by Titus-von-Koeller** [comment] 2023-12-11 15:04
@younesbelkada I think we have to reopen this, due to @poedator's comment. It would be good to cook up a minimal example of the issue and validate

> I tested the packages versions and it appears that the error happens with peft==0.7.0
It was not happening with peft==0.6.2 and 0.6.0

> Then I tested older bnb releases and found that the error still happens with bitsandbytes==0.40.2 and 0.41.1. So this issue seems to be related not to my recent quantization PRs but rather to something on PEFT side.

I won't have time to look at this right away, so if this is urgent, happy if someone else takes the lead.

**Comment by Titus-von-Koeller** [comment] 2023-12-11 15:06
What's strange is that I could reproduce the issue and then it went away with the bnb version change. It's true however, that I didn't pin the PEFT version, but that was within minutes of each other (so would have expected them to be the same). This needs further verification.

**Comment by BenjaminBossan** [comment] 2023-12-11 15:51
Hi, maybe I'm out of the loop, but when I ran the notebook, I saw there was a mistake where the model is loaded as:

```python
model = get_peft_model(model, lora_config)
```

First of all, the model should be loaded using `PeftModel.from_pretrained`, second, the `model` that is being passed should be the base model, not the PEFT model. So when I make this change, the notebook runs for me:

```python
- model = get_peft_model(model, lora_config)
+ base_model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map={"":0})
+ peft_model = PeftModel.from_pretrained(base_model, <PATH>)
```

If this used to work with an older PEFT version, it was almost surely not doing what the intent was.

**Comment by Titus-von-Koeller** [comment] 2024-01-15 16:12
I think we should fix the notebook source code then, since this is the entrypoint of many new users to using BNB.

@younesbelkada, do you know where the NB source code is hosted? I couldn't find it in the bnb or qlora repos.

**Closed** 2024-02-17 15:04 UTC
