### ISSUE TITLE
Support HQQ method.

### ISSUE THREAD

**Issue by Minami-su** [huggingface/peft#1616] opened 2024-04-03 06:20 UTC
peft version 0.10.0
```
base_model=Qwen1.5-14B-Chat_llamafy-1bit
model = AutoHQQHFModel.from_quantized(base_model).half().cuda()
modules = find_all_linear_names(model)
# Add Peft
######################################################################################
config = LoraConfig(
r=lora_r,
lora_alpha=lora_alpha,
target_modules=modules,
lora_dropout=lora_dropout,
bias="none",
task_type="CAUSAL_LM",
)
model = get_peft_model(model, config)
```
Target module HQQLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.

**Comment by BenjaminBossan** [comment] 2024-04-03 10:19
Indeed, HQQ is currently not implemented in PEFT. They have their own [LoRA implementation](https://github.com/mobiusml/hqq?tab=readme-ov-file#peft-training), so you can check that out, but from what I can tell, it's not as feature complete as the PEFT LoRA implementation.

I checked out the [HQQ LoRA layer](https://github.com/mobiusml/hqq/blob/3bb6bbb7088e02fe41c9cffae0b5b733473f1066/hqq/core/peft.py#L31) and I think it should be possible to port it to PEFT so that PEFT can natively support HQQ. This would require a few modifications to make it compatible and to support more PEFT features (like multiple adapters).

If this is something you're interested in adding to PEFT, let us know. Otherwise, we may take a look at it in the future.

Also pinging @younesbelkada for when he's back in office.

**Comment by fahadh4ilyas** [comment] 2024-04-03 13:26
I make my LoRA implementation for HQQ in my fork to [peft](https://github.com/fahadh4ilyas/peft.git). I'm not sure if I could do a pull request because I don't know if this implementation is right or not.

**Comment by Minami-su** [comment] 2024-04-03 13:34
> I make my LoRA implementation for HQQ in my fork to [peft](https://github.com/fahadh4ilyas/peft.git). I'm not sure if I could do a pull request because I don't know if this implementation is right or not.

Traceback (most recent call last):
  File "/root/autodl-tmp/merge-with-lora-hqq2.py", line 25, in <module>
    model = PeftModel.from_pretrained(model, lora_patch,device_map={"": "cpu"},torch_dtype=torch.float16)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/peft_model.py", line 387, in from_pretrained
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/peft_model.py", line 1212, in __init__
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/peft_model.py", line 131, in __init__
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/lora/model.py", line 136, in __init__
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/tuners_utils.py", line 165, in __init__
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/tuners_utils.py", line 342, in inject_adapter
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/lora/model.py", line 220, in _create_and_replace
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/lora/model.py", line 301, in _create_new_module
ValueError: Target module HQQLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.

**Comment by BenjaminBossan** [comment] 2024-04-03 14:44
> I make my LoRA implementation for HQQ in my fork to [peft](https://github.com/fahadh4ilyas/peft.git). I'm not sure if I could do a pull request because I don't know if this implementation is right or not.

Thanks for the link. I did a quick check on the [diff](https://github.com/huggingface/peft/compare/main...fahadh4ilyas:peft:hqq-lora) and it looks reasonable to me. It probably would require a few changes to make it fully PEFT-compatible and as you mentioned, we would have to verify the correctness (maybe we can compare outputs with the HQQ PEFT implementation). So if you're interested in giving this a try, feel free to open a (draft) PR and we can iterate from there.

**Comment by fahadh4ilyas** [comment] 2024-04-03 14:54
@Minami-su use the hqq-lora branch, not the main branch.

**Comment by fahadh4ilyas** [comment] 2024-04-03 14:57
@BenjaminBossan the problem is preparing for k-bit training because currently there is no sign nor param that show that current model is quantized with HQQ. That's why I change some config in my HQQ fork so that peft could know that the model is quantized with HQQ. I already test training. Forward dan backward works without any problem. I didn't check training result though.

**Comment by BenjaminBossan** [comment] 2024-04-03 15:09
> the problem is preparing for k-bit training because currently there is no sign nor param that show that current model is quantized with HQQ. That's why I change some config in my HQQ fork so that peft could know that the model is quantized with HQQ.

That's okay. We can make such changes as long as they're backwards compatible. If you open a PR, we can discuss there whether your solution is the best one or if we can find something better.

**Comment by fahadh4ilyas** [comment] 2024-04-03 15:25
@BenjaminBossan added to #1618

**Comment by Minami-su** [comment] 2024-04-03 23:50
> @Minami-su use the hqq-lora branch, not the main branch.

Ok,can be used.
![image](https://github.com/huggingface/peft/assets/76865636/a9b31e65-7f58-4098-af6e-a0d0e9d08ba5)

**Comment by Minami-su** [comment] 2024-04-04 00:05
@fahadh4ilyas How to merge lora with 1bit model?
```
Traceback (most recent call last):
  File "/root/autodl-tmp/merge-with-lora-hqq2.py", line 26, in <module>
    model = model.merge_and_unload()
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/lora/model.py", line 785, in merge_and_unload
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/lora/model.py", line 439, in _unload_and_optionally_merge
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/peft-0.10.1.dev0-py3.10.egg/peft/tuners/lora/hqq.py", line 80, in merge
TypeError: 'NoneType' object is not a mapping
```

**Comment by BenjaminBossan** [comment] 2024-05-03 15:11
#1618 has been merged :tada:

**Closed by BenjaminBossan** 2024-05-03 15:11 UTC
