### ISSUE TITLE
Got error when trying to merge qlora to model

### ISSUE THREAD

**Issue by khiempm209** [huggingface/peft#1203] opened 2023-11-30 18:31 UTC
### System Info

When i tried to merge qlora to model, i got this error. It seem some arguments are not added to the function 

```
File /opt/conda/lib/python3.10/site-packages/peft/peft_model.py:304, in PeftModel.from_pretrained(cls, model, model_id, adapter_name, is_trainable, config, **kwargs)
    302 # load the config
    303 if config is None:
--> 304     config = PEFT_TYPE_TO_CONFIG_MAPPING[
    305         PeftConfig._get_peft_type(
    306             model_id,
    307             subfolder=kwargs.get("subfolder", None),
    308             revision=kwargs.get("revision", None),
    309             cache_dir=kwargs.get("cache_dir", None),
    310             use_auth_token=kwargs.get("use_auth_token", None),
    311         )
    312     ].from_pretrained(model_id, **kwargs)
    313 elif isinstance(config, PeftConfig):
    314     config.inference_mode = not is_trainable

File /opt/conda/lib/python3.10/site-packages/peft/config.py:134, in PeftConfigMixin.from_pretrained(cls, pretrained_model_name_or_path, subfolder, **kwargs)
    131     config_cls = cls
    133 kwargs = {**class_kwargs, **loaded_attributes}
--> 134 config = config_cls(**kwargs)
    135 return config

TypeError: LoraConfig.__init__() got an unexpected keyword argument 'loftq_config'
```

### Who can help?

@pacman100  @younesbelkada @sayakpaul 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```
vi_model_final = PeftModel.from_pretrained(vi_model_merge, model_name)
vi_model_final = vi_model_final.merge_and_unload()
vi_model_final.eval()

File /opt/conda/lib/python3.10/site-packages/peft/peft_model.py:304, in PeftModel.from_pretrained(cls, model, model_id, adapter_name, is_trainable, config, **kwargs)
    302 # load the config
    303 if config is None:
--> 304     config = PEFT_TYPE_TO_CONFIG_MAPPING[
    305         PeftConfig._get_peft_type(
    306             model_id,
    307             subfolder=kwargs.get("subfolder", None),
    308             revision=kwargs.get("revision", None),
    309             cache_dir=kwargs.get("cache_dir", None),
    310             use_auth_token=kwargs.get("use_auth_token", None),
    311         )
    312     ].from_pretrained(model_id, **kwargs)
    313 elif isinstance(config, PeftConfig):
    314     config.inference_mode = not is_trainable

File /opt/conda/lib/python3.10/site-packages/peft/config.py:134, in PeftConfigMixin.from_pretrained(cls, pretrained_model_name_or_path, subfolder, **kwargs)
    131     config_cls = cls
    133 kwargs = {**class_kwargs, **loaded_attributes}
--> 134 config = config_cls(**kwargs)
    135 return config

TypeError: LoraConfig.__init__() got an unexpected keyword argument 'loftq_config'
```

### Expected behavior

Add the necessary argument to the function

**Comment by sayakpaul** [comment] 2023-12-01 01:39
Could you provide a reproducible code snippet?

**Comment by khiempm209** [comment] 2023-12-01 03:07
when i try to merge my lora to Mistral model like this:

model_name = "meta-math/MetaMath-Mistral-7B"
bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)
n_gpus = torch.cuda.device_count()
max_memory = f'{40960}MB'

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
    max_memory = {i: max_memory for i in range(n_gpus)},
    torch_dtype=torch.bfloat16,
)
tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=True)
tokenizer.pad_token = tokenizer.eos_token
vi_model_final = PeftModel.from_pretrained(model, 'wanderer2k1/mammoth-7b-intruct-vietnamese')
vi_model_final = vi_model_final.merge_and_unload()

I got this error in the 2nd line from the bottom:

![check_error](https://github.com/huggingface/peft/assets/119430607/a838c936-1bbd-4f98-a8c8-5d3f16a16063)

**Comment by BenjaminBossan** [comment] 2023-12-01 10:45
Hi, is it possible that the adapter you're trying to load was saved with a more recent PEFT version than what you're using to load it? We very recently merged `LoftQ` support, which results in a new entry in the `adapter_config.json` for `LoftQ`. It appears like you're trying to load the adapter with an older PEFT version, which does not yet know about the new entry in the config.

You could either try to update your environment by installing PEFT from the main branch, or you could manually edit the `adapter_config.json` inside of `wanderer2k1/mammoth-7b-intruct-vietnamese` and remove the field `loftq_config`.

**Comment by YunzeSong** [comment] 2023-12-17 02:12
> I second what @BenjaminBossan said, I believe installing PEFT from source should fix your issue
> 
> ```shell
> pip install -U git+https://github.com/huggingface/peft.git
> ```
> 
> Can you try that out and let us know if this works?

It works for me. Thank you a lot

**Comment by younesbelkada** [comment] 2023-12-18 09:27
Thanks ! Closing the issue then

**Closed by younesbelkada** 2023-12-18 09:27 UTC

**Comment by yaokunkun** [comment] 2024-02-06 08:10
> I second what @BenjaminBossan said, I believe installing PEFT from source should fix your issue
> 
> ```shell
> pip install -U git+https://github.com/huggingface/peft.git
> ```
> 
> Can you try that out and let us know if this works?

Thanks! It works for me.

**Comment by BenjaminBossan** [comment] 2024-02-06 14:31
Just to note, installing the latest PEFT version from pypi (`pip install peft`) should be sufficient now, since we had a release in the meantime. Installing from source should not be required anymore.
