### ISSUE TITLE
TypeError: LlamaModel.forward() got an unexpected keyword argument 'labels' when using LoRA on Llama 3.2

### ISSUE THREAD

**Issue by hoang1645** [huggingface/peft#2243] opened 2024-12-01 15:51 UTC
### System Info

Python version: 3.12.3
Platform: Ubuntu 24.04 (WSL2)
 `peft==0.13.2, accelerate==1.0.1, transformers==4.46.3`

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Code:
```python
import torch
from transformers import AutoModel, BitsAndBytesConfig as BnBConfig, AutoTokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling
from peft import LoraConfig, LoraModel, prepare_model_for_kbit_training, get_peft_model
from peft.optimizers import create_loraplus_optimizer
from bitsandbytes.optim import PagedAdamW8bit


quantization_config = BnBConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,    
)

lora_config = LoraConfig(
    r=8,
    target_modules="all-linear",
    lora_alpha=32,
    task_type="CAUSAL_LM",
    init_lora_weights="loftq"
)

model = AutoModel.from_pretrained("meta-llama/Llama-3.2-1B-instruct", quantization_config=quantization_config,
                                             torch_dtype=torch.bfloat16)
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B-instruct")
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id 
model = get_peft_model(model, lora_config)
model = prepare_model_for_kbit_training(model)

tokens = tokenizer("Hello, my dog is cute", return_tensors="pt")
output = model(**tokens)
```

Error:
```
Traceback (most recent call last):
  File "/mnt/d/stuff/other/test/main.py", line 46, in <module>
    output = model(**tokens)
             ^^^^^^^^^^^^^^^
  File "/home/hoang/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hoang/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hoang/.local/lib/python3.12/site-packages/peft/peft_model.py", line 1644, in forward
    return self.base_model(
           ^^^^^^^^^^^^^^^^
  File "/home/hoang/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hoang/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hoang/.local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py", line 197, in forward
    return self.model.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hoang/.local/lib/python3.12/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LlamaModel.forward() got an unexpected keyword argument 'labels'
```

### Expected behavior

The script runs normally without errors.

**Comment by BenjaminBossan** [comment] 2024-12-02 10:28
The error should disappear if you load the model using `AutoModelForCausalLM`:

```python
model = AutoModelForCausalLM.from_pretrained(...)
```

**Comment by antonItachi** [comment] 2024-12-04 16:38
@BenjaminBossan Yes, I agree. I believe the error occurs because AutoModel does not include the lm_head layer, which is responsible for converting the model's outputs into logits. This is crucial when labels are provided, as it directly computes the loss during training.

**Comment by BenjaminBossan** [comment] 2024-12-05 10:36
Great, so it sounds like your problem has been resolved. I'll close this issue then, feel free to re-open in case the error did not go away.

**Closed by BenjaminBossan** 2024-12-05 10:36 UTC

**Comment by antonItachi** [comment] 2024-12-05 10:52
It was not my error, but you can close it anyway,  xD

**Comment by BenjaminBossan** [comment] 2024-12-05 10:54
Closing just means that the issue is completed and no further work is needed ;)

**Comment by antonItachi** [comment] 2024-12-05 17:05
Actually, I came across your GitHub profile and just wanted to say how inspiring it is to see someone with such incredible work. It’s rare to stumble upon people who are so deeply involved in AI and making a real difference. It’s truly motivating!

Keep up the amazing work!
