### ISSUE TITLE
Issues with loading and unload multiple adapter for inference?

### ISSUE THREAD

**Issue by user06039** [huggingface/peft#957] opened 2023-09-24 15:21 UTC
I have one base llama-2 model and I have trained 10 different Lora adapters (Each finetuned for a different task).

I am trying to benchmark, time to taken to load and unload these adapters to the base llama model.

```
base_model = AutoModelForCausalLM.from_pretrained(
        base_llama2_path,
        torch_dtype=torch.bfloat16,
        device_map="auto",
    )
tokenizer = AutoTokenizer.from_pretrained(base_llama2_path)
base_model = PeftModel.from_pretrained(base_model, "./models/test", adapter_name="test", device_map="balanced")
base_model = PeftModel.from_pretrained(base_model, "./models/ner", adapter_name="ner", device_map="balanced")
```

Here when I load "./models/test", it's modifying the "base_model" that I pass, then when I try to "./models/ner" adapter, I don't know if this working but when I try to do ,

base_model.set_adapter("test") -> this is not working, (Is this a bug?)
base_model.set_adapter("ner") -> this is working.

How can I do below things in optimized way?
- I want to load one base llama model and keep loading multiple lora adapters that can fit on my GPU and let's say once my GPU is full and I can't load any more lora adapter, I want to delete one of the adapter that is already loaded and load a new model.

I also tried this type of approach, 

```
base_model = AutoModelForCausalLM.from_pretrained(
        base_llama2_path,
        torch_dtype=torch.bfloat16,
        device_map="auto",
    )
tokenizer = AutoTokenizer.from_pretrained(base_llama2_path)
model = PeftModel.from_pretrained(base_model, "./models/test", adapter_name="test", device_map="balanced")
base_model = model.unload()
model = PeftModel.from_pretrained(base_model, "./models/ner", adapter_name="ner", device_map="balanced")
```
but the problem is that last "model" does not contain the "Test" adapter only the "ner" adapter. I want to have both in memory as long as it fits on my GPU (A100 40GB).

**What's happening here, can someone point me in correct direction, what's the correct way to load and unload lora adapters during run-time for inference?** I couldn't find much on internet that is useful.

**Comment by BenjaminBossan** [comment] 2023-09-25 08:33
I agree this is not well documented. The way to go is to use the `load_adapter` method for each adapter after the first one:

```python
model = PeftModel.from_pretrained(base_model, "adapter1")
model.load_adapter("adapter2")
```

**Comment by user06039** [comment] 2023-09-25 10:18
> I agree this is not well documented. The way to go is to use the `load_adapter` method for each adapter after the first one:
> 
> ```python
> model = PeftModel.from_pretrained(base_model, "adapter1")
> model.load_adapter("adapter2")
> ```

Thank you soo much for providing the help. I really appreciate it. I couldn't find proper documentation on this anywhere.

I had one follow-up to this, I loaded around `20` adapters to the `base_model` which could fit into my GPU. 

Now, how can I hot-swap one of the `20 adapters` with a new adapter that I trained very recently? How can I do it?

**Comment by user06039** [comment] 2023-09-25 10:39
> > I couldn't find proper documentation on this anywhere.
> 
> Yes, we need to document that for sure.
> 
> > how can I hot-swap one of the `20 adapters` with a new adapter that I trained very recently?
> 
> There is no method to hot-swap an adapter. You would have to call `delete_adapter` for the one you want to remove and then call `load_adapter` again. If you use the same name, it should have the same effect, but it's not an "atomic" operation, if that's what you're hoping for.

@BenjaminBossan  Thank you. I tried the `delete_adapter` but it's not freeing up the the GPU space (i.e., I noted the nvidia-smi GPU usage)? Is there any way I can free up the GPU space after deletion of the adapter?

**Comment by BenjaminBossan** [comment] 2023-09-25 14:02
Could you check of a call to `torch.cuda.empty_cache()` frees the memory? Otherwise, maybe the gc will pick up when the new adapter is added under the same name, not sure.

**Comment by user06039** [comment] 2023-09-25 14:45
Yes, `torch.cuda.empty_cache()` did indeed free up the GPU memory after deleting an adapter.  

Is using `model.load_adapter("adapter2")` the most optimised way to load an adapter? I see that it's taking around a second (i.e., 1.2-1.7 sec) to load an adapter using cuda. Can we somehow optimize or reduce this latency? (or) do you personally know any optimisation to reduce the latency in loading these delta weights?

**Comment by user06039** [comment] 2023-09-25 22:24
> Interesting, does this take longer than when you initially load the adapters? Maybe there is some room for optimization, we would need to run a profiler, but AFAIK there is no faster method at the moment.

@BenjaminBossan 

This is what I noticed,

model = PeftModel.from_pretrained(base_model, "adapter1") -> first load took around 30 seconds on A100 40GB.

Then each time I add a new adapter, time taken increases, 

model.load_adapter("adapter2") --> 1.0 seconds
model.load_adapter("adapter3") --> 1.1 seconds
model.load_adapter("adapter4") --> 1.2 seconds
....
model.load_adapter("adapter40") --> 1.9 seconds
...
model.load_adapter("adapter90") --> 2.8 seconds

Is this a common behaviour? Each Lora Adapter has exactly same configuration (i.e., parameters, rank etc.,).

**Comment by BenjaminBossan** [comment] 2023-09-26 10:24
Interesting, so there is a big jump in time from 1st adapter to 2nd, then a slow increase for each subsequent one. I think this requires some proper profiling to identify the issue, not sure what the reason is. This will probably take some time to debug. I hope that in the meantime, you can still continue working despite the slow down.

**Comment by user06039** [comment] 2023-09-26 11:58
@BenjaminBossan  Thank for the follow-ups. I think loading times are fine with us mostly, but one another interesting observation and a potential roadblock is that,

When I do inference using below method the time taken is let's say 4.2 seconds with some params,

```
model = PeftModel.from_pretrained(base_model, "adapter1")
model.load_adapter("adapter2")

model.set_adapter("adapter2")
model.generate(**inputs)
```

Now when we do inference using this method, it's taking around 2.8 seconds with same params as above,

Above inference method is taking around 45-50% more time compared to this below method,

```
model = PeftModel.from_pretrained(base_model, "adapter2")
model = model.merge_and_unload()
model.generate(**inputs)
```


Can you tell me why `merge_and_upload` might provide faster inference compared to detachable adapter code?

**Comment by BenjaminBossan** [comment] 2023-09-26 12:21
This behavior is expected. Remember that LoRA adds new parameters on top of the existing ones. Then, under the hood, we basically do something like this (pseudo-code): 

```python
def forward(self, x):
    activations = ...
    lora_activations = ...
    activations = base_activations + lora_activations
```

When you merge the LoRA weights, the last two lines can be skipped, resulting in faster inference. This is a trade-off that always comes with LoRA. The exact amount of overhead depends on the model architecture and LoRA config.

**Comment by user06039** [comment] 2023-09-26 13:24
@BenjaminBossan Thank you for sharing the context regarding the issue.

**Comment by BenjaminBossan** [comment] 2023-09-29 15:11
Hey @user06039, I created a separate issue to track the problem with the slowdown caused by adding more and more adapters (#981). The original issue should be solved, so I'll close this issue.

**Closed by BenjaminBossan** 2023-09-29 15:11 UTC

**Comment by lemingshen** [comment] 2024-09-30 01:53
> I agree this is not well documented. The way to go is to use the `load_adapter` method for each adapter after the first one:
> 
> ```python
> model = PeftModel.from_pretrained(base_model, "adapter1")
> model.load_adapter("adapter2")
> ```

When using this code, I met the following problem:
![image](https://github.com/user-attachments/assets/01cd5c32-efbe-4b27-9f43-d66caa54808a)

Does that mean I need to tune another adapter without bias?
