### ISSUE TITLE
exclude_modules to keep specific layers or other quirky components out of a target_modules selection

### ISSUE THREAD

**Issue by bghira** [huggingface/peft#2044] opened 2024-08-29 13:56 UTC
### Feature request

The LoraConfig class should accept an optional `exclude_modules` list of regular expressions in an analogue to `target_modules` that then should be referenced when matching against entries from `target_modules`.

### Motivation

Targeting `proj_out` and `proj_mlp` on some models greatly improves the results, but we find that the effect is more reliable and robust if the final proj_out and proj_mlp layers are excluded.

### Your contribution

I can quickly integrate, test, and make use of this feature in [bghira/simpletuner](https://github.com/bghira/simpletuner)

I'm not sure I'll have time to submit a PR in the next two weeks, but after that perhaps I will be able to. Someone who grabs it before then will be much appreciated 💌

**Comment by BenjaminBossan** [comment] 2024-08-29 14:56
Thanks for opening this feature request. You're not the first one who would like to have this feature. If you or someone else wants to work on the PR, contributions are welcome.

That said, I just wanted to ask if you know that there are already ways to achieve this. One way is to use `layers_pattern`, which is used to match the string, and `layers_to_transform`, which is a list of indices of the layers you would like to match. More in the [docs](https://huggingface.co/docs/peft/v0.12.0/en/package_reference/lora#peft.LoraConfig). It's a bit of an obscure feature but sounds like it is exactly what you require.

The most flexible way to tackle this type of problem is, however, to pass a string to `target_modules`. In this case a regex match is applied. This pretty much allows all kinds of fancy patterns, such as matching all `proj_out` except for `layers.31.proj_out`, just as an example.

**Comment by bghira** [comment] 2024-08-29 15:05
oh, i see. so you are suggesting i programmatically search the keys and build a list of targets that match my exclude and target patterns! that is pretty good. maybe it's enough

**Comment by BenjaminBossan** [comment] 2024-08-29 15:54
What I meant is something like this: Say I have `facebook/opt-125m`. This model has 12 attention layers. Say I want to match `fc1` but only layers 0-10, not 11. I can achieve this by passing:

```python
config = LoraConfig(target_modules=r".*\.(?!11)\d+\.fc1$")
```

**Comment by JINO-ROHIT** [comment] 2024-09-24 10:53
Hi @BenjaminBossan just trying to understand and if possible would like to take this up and contribute.

The issue is to add an extra exclude params in the lora config to not use specific layers right? Is this needed since passing a 'fc' layers in target modules matches across all the layers?

**Comment by JINO-ROHIT** [comment] 2024-09-25 10:14
alright @BenjaminBossan thanks, id like to take this up

**Comment by BenjaminBossan** [comment] 2024-10-21 08:57
Resolved via #2102. At the moment, using this requires installing PEFT from source.

**Closed by BenjaminBossan** 2024-10-21 08:57 UTC
Labels: enhancement, contributions-welcome
