### ISSUE TITLE
QLoRA example results in errors

### ISSUE THREAD

**Issue by avisoori-databricks** [huggingface/peft#498] opened 2023-05-24 19:39 UTC
First of all, thank you for all your amazing work. I am reading through this blog: https://huggingface.co/blog/4bit-transformers-bitsandbytes and tried to run the example in the [Fine tuning Google Colab notebook](https://colab.research.google.com/drive/1VoYNfYDKcKRQRor98Zbf2-9VQTtGJ24k?usp=sharing) it results in the following error in the trainer.train() cell:

RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 125 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

So the example does not work as is or with another model, e.g. GPT-neo-2.7B. Is there a way to resolve this? Thanks

**Comment by younesbelkada** [comment] 2023-06-26 07:39
Hi @avisoori-databricks 
Do you still face the issue with the main branch of `transformers`, `accelerate` & `peft` ?

**Comment by shwet-mishra** [comment] 2023-07-17 06:22
Facing similar error:
Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
**_Parameter at index 255 with name base_model.model.transformer.h.31.mlp.dense_4h_to_h.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration._**

**Closed** 2023-08-19 15:03 UTC
