### ISSUE TITLE
Issues with set_peft_model_state_dict, dictionary not properly updating.

### ISSUE THREAD

**Issue by ElleLeonne** [huggingface/peft#285] opened 2023-04-08 13:59 UTC
So in the previous peft version, before the recent adalora changes, set_peft_model_state_dict returned a wrapped model object.

Now, it appears to function as a mutator (returns None). So I changed my code appropriately.
![image](https://user-images.githubusercontent.com/87243032/230725101-0ed5a822-e793-4400-af77-0caec7e07857.png)
I am trying to further fine-tune an existing lora adapter that I have. The problem appears to be that it's not actually updating the state_dict at all, because when I resume training, not only are all the training parameters off, but I also have a ton of dict keys that are mismatched.
![image](https://user-images.githubusercontent.com/87243032/230725170-cb411385-4ef4-414b-904f-fd8864654fd4.png)
and
![image](https://user-images.githubusercontent.com/87243032/230725194-19ae2718-3001-4567-9a58-40a4870ca9c4.png)
Epoch should be 6, but thinks it's 1.3, etc

Retraining the adapter from scratch does nothing. Does anyone have any ideas?

**Comment by diegomontoya** [comment] 2023-04-09 03:09
@ElleLeonne 

I am checking the ```set_peft_model_state_dict``` diffs and the AdaLora changes only added an if condition that should not have broken anything as far as llama lora training goes.  I'm getting more and more confused on all the peft/transformer changes recently that has broken llama code in multiple places at once.

```
def set_peft_model_state_dict(model, peft_model_state_dict):
    """
    Set the state dict of the Peft model.
    Args:
        model ([`PeftModel`]): The Peft model.
        peft_model_state_dict (`dict`): The state dict of the Peft model.
    """
    if model.peft_config.peft_type == PeftType.ADALORA:
        rank_pattern = model.peft_config.rank_pattern
        if rank_pattern:
            model.base_model.resize_modules_by_rank_pattern(rank_pattern)
    model.load_state_dict(peft_model_state_dict, strict=False)

    if model.peft_config.peft_type not in (PeftType.LORA, PeftType.ADALORA):
        model.prompt_encoder.embedding.load_state_dict(
            {"weight": peft_model_state_dict["prompt_embeddings"]}, strict=True
        )
    return model
```

https://github.com/huggingface/peft/blob/382b178911edff38c1ff619bbac2ba556bd2276b/src/peft/utils/save_and_load.py#L65

**Comment by ElleLeonne** [comment] 2023-04-09 03:13
Wait, why does this function return a model object? That wasn't there this morning when I was trying to debug...

The plot thickens...

**Comment by pacman100** [comment] 2023-04-09 05:23
Hello @ElleLeonne,

We made recent changes to support multiple adapter inference and training. As such, there was a need to load the save adapters with their params in frozen mode without, that explains the  `all the training parameters off`. To have the trainable params of adapters when loading, either set `inference_mode=False` in the PeftConfig or use `from_pretrained` method with param `is_trainable=True`.

I'm unable to reproduce any errors. Below are the screenshots of the code snippets along with the outputs, everything is working as expected.

<img width="1125" alt="Screenshot 2023-04-09 at 10 48 47 AM" src="https://user-images.githubusercontent.com/13534540/230755792-99c984c9-392d-4d7e-a516-a77882950afc.png">

<img width="1109" alt="Screenshot 2023-04-09 at 10 49 02 AM" src="https://user-images.githubusercontent.com/13534540/230755797-c38356cc-5e14-4ff6-b3e2-5b2cb74ada80.png">

Please provide us with minimal reproducible scripts that we can execute to further deep dive and resolve the issues, if any.

**Comment by pacman100** [comment] 2023-04-09 05:27
@ElleLeonne, we have tried our best to not have any breaking changes, although it might be the case that some changes are breaking ones, e.g., the `set_peft_model_state_dict ` being a mutator.

**Comment by ElleLeonne** [comment] 2023-04-09 15:10
@pacman100 

Ah, I see. You're just loading the adapter. I can do that just fine.

My issue comes from attempting to load the checkpoint weights, and continue training from that point.

I'll work on trying to get something reproducible together, but maybe that sparks a thought in the meantime.

**Comment by ElleLeonne** [comment] 2023-04-09 16:22
@pacman100 
Alright, I've managed to reproduce it in slim form. [Code is here](https://github.com/ElleLeonne/ML-playground-dump/blob/main/testing.py)
![image](https://user-images.githubusercontent.com/87243032/230783538-a568d0f5-08c0-45ce-90a5-f9a7e0173b49.png)
I trained a generic adapter just to produce something, then attempted to load the weights of the checkpoint file to resume training.

And here's your [PeftModel version](https://github.com/ElleLeonne/ML-playground-dump/blob/main/testingPeftModel.py).

Both result in the weights issue.

![image](https://user-images.githubusercontent.com/87243032/230784293-46691f84-669f-430f-ad1c-4b67937d2e47.png)
![image](https://user-images.githubusercontent.com/87243032/230784315-1e76c7ae-bb5b-4782-ba4f-32f89bb3f848.png)

I'm going to work on trying to find a way to merge the weights, but if I don't provide an update, assume I haven't figured anything out yet.

**Comment by ElleLeonne** [comment] 2023-04-09 17:58
Also gonna rope in @AngainorDev who made the original continue from checkpoint script.

I realize you said to ignore a "missing keys" error, but the unexpected keys thing seems to be a product of the recent update, and the weights don't appear to be merging right as a result.

**Comment by AngainorDev** [comment] 2023-04-11 16:18
@ElleLeonne 
Did you try with  set inference_mode=False in the PeftConfig ?
line 25 of your minimal code, try adding add peft_config.inference_mode=False

**Comment by ElleLeonne** [comment] 2023-04-12 01:03
> 

I just got home and tried it, same issue with unexpected keys. Both on my minimal script, and my live implementation

**Comment by lywinged** [comment] 2023-04-13 13:21
> I just got home and tried it, same issue with unexpected keys. Both on my minimal script, and my live implementation

The "def get_peft_model_state_dict" is not updating as well, because the last line 
"to_return = {k.replace(f".{adapter_name}", ""): v for k, v in to_return.items()}"  in /peft/utils/save_and_load.py
overwrites our adapter_model.bin. Comment it, then it works fine.

**Comment by pacman100** [comment] 2023-04-18 10:22
Let me know if this PR fixes the issues: https://github.com/tloen/alpaca-lora/pull/359

**Comment by lywinged** [comment] 2023-04-19 01:23
> Let me know if this PR fixes the issues: [tloen/alpaca-lora#359](https://github.com/tloen/alpaca-lora/pull/359)

It's fixed now. Just test it.

**Comment by ElleLeonne** [comment] 2023-04-21 13:50
https://github.com/tloen/alpaca-lora/pull/359#issuecomment-1517859182
@lywinged

I don't think so. My impression is that my use-case was misinterpreted. This allows us to load an adapter, and then train a new second adapter, rather than continuing from an old adapter. My use-case was continuing training from an old adapter, so that I didn't need to retrain a new adapter every single time I acquired new data.

**Comment by shibing624** [comment] 2023-05-04 11:37
> Code is here

how to work? i mean how to predict with the new lora model.

 i trained a new lora model, from llama-7b and tloen/alpaca-lora-7b, and i get a new lora model, how to add `tloen/alpaca-lora-7b` and my own lora model.

**Closed** 2023-06-05 15:04 UTC
