### ISSUE TITLE
AttributeError: 'Linear4bit' object has no attribute 'compute_dtype'

### ISSUE THREAD

**Issue by Margaretmmh** [huggingface/peft#1235] opened 2023-12-07 20:31 UTC
### System Info

System: Google colab V100 High RAM

### Who can help?

@pacman100 @younesbelkada @sayakpaul

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

lora_config = LoraConfig.from_pretrained('outputs')
model = get_peft_model(model,lora_config)

### Expected behavior

I'm fine tuning a Llama2 model with Qlora on a medical dataset and the error happened when I run the snippet above. Please kindly help. I attached the notebook link for your reference. [https://colab.research.google.com/drive/1zOrLTIb9AmFl-RviGpNfxBXz-gZiBZ_3?usp=sharing](url)

**Comment by younesbelkada** [comment] 2023-12-08 08:48
Hi @Margaretmmh 
It seems to be a duplicate of https://github.com/huggingface/peft/issues/1209 
Can you try to upgrade `bitsandbytes` as suggested here: https://github.com/huggingface/peft/issues/1209#issuecomment-1844983371

**Comment by NisargBhavsar25** [comment] 2023-12-08 10:16
It's an issue with how the new version of `bitsandbytes` library handles dtypes. Try changing the version to the following:

`python -m pip install bitsandbytes --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui`

**Comment by BenjaminBossan** [comment] 2023-12-08 16:32
> Try changing the version to the following:

Just a general comment to users, please always be careful when installing from unofficial sources. I don't know this user and I'm not suggesting they're malicious, this is a just a general precaution.

**Comment by pod2c** [comment] 2023-12-09 04:26
> Hi @Margaretmmh It seems to be a duplicate of #1209 Can you try to upgrade `bitsandbytes` as suggested here: [#1209 (comment)](https://github.com/huggingface/peft/issues/1209#issuecomment-1844983371)

Hi, it seems that upgrading to latest version didn't work for me, my code still had the same error
![Uploading 屏幕截图 2023-12-09 114918.png…]()

**Comment by Liweixin22** [comment] 2023-12-09 15:39
After install bitsandbytes  == 0.41.3, my code still had the same error, too!

**Comment by pod2c** [comment] 2023-12-10 04:20
> After install bitsandbytes == 0.41.3, my code still had the same error, too!

Problem has been solved. You can try installing an old version of peft like 0.6.2. The problem seems to be on the peft version.
Reference link: [https://github.com/huggingface/peft/issues/1209#issuecomment-1848683685](url)

**Comment by Liweixin22** [comment] 2023-12-12 06:54
> > After install bitsandbytes == 0.41.3, my code still had the same error, too!
> 
> Problem has been solved. You can try installing an old version of peft like 0.6.2. The problem seems to be on the peft version. Reference link: [https://github.com/huggingface/peft/issues/1209#issuecomment-1848683685](url)

Thx!
My problem has beed solved!

**Comment by younesbelkada** [comment] 2024-01-08 05:56
Seems to be solved on the latest bnb release, let us know if you still face the issue

**Closed** 2024-01-08 05:55 UTC
