### ISSUE TITLE
Int8 training example error with multi-gpu - flan-t5

### ISSUE THREAD

**Issue by djaym7** [huggingface/peft#205] opened 2023-03-21 16:28 UTC
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

**Comment by younesbelkada** [comment] 2023-03-21 17:25
hi @djaym7 
Can you please share a reproducible script?
Thanks!

**Comment by djaym7** [comment] 2023-03-21 17:28
![temp](https://user-images.githubusercontent.com/12378820/226692535-faf3d6a4-0431-4590-8381-9162d225d30e.jpg)

Rename to temp.ipynb .

**Comment by djaym7** [comment] 2023-03-21 17:29
To reproduce, option 2 is to comment out os.environ['CUDA_VISIBLE_DEVICES']='0' line in this example https://github.com/huggingface/peft/blob/main/examples/int8_training/Finetune_flan_t5_large_bnb_peft.ipynb and run it on multi-gpu instance.

**Comment by macabdul9** [comment] 2023-03-31 01:36
Any update on this? @djaym7  did you manage to fix it?

**Comment by djaym7** [comment] 2023-03-31 03:18
No I didn't

**Comment by younesbelkada** [comment] 2023-03-31 07:42
hey @djaym7 @macabdul9 
In multi-GPU setup you need to add the following: 
```python
setattr(model, 'model_parallel', True)
setattr(model, 'is_parallelizable', True)
```
right after creating the model. This should solve your issue

**Comment by Shreyans92** [comment] 2023-03-31 14:16
@younesbelkada the above mentioned change is not working. I am getting following error:
AttributeError:'T5Stack' object has no attribute 'first_device'.  
Can you check once?

**Comment by younesbelkada** [comment] 2023-03-31 14:22
@pacman100 I believe because T5 still uses the [old `parallelize` API](https://github.com/huggingface/transformers/blob/d143087d189a183b153090c8b37daa6c7c031039/src/transformers/models/t5/modeling_t5.py#L783). Could you try to just add `setattr(model, 'model_parallel', True)` instead of the 2 lines?

**Comment by Shreyans92** [comment] 2023-03-31 14:37
@younesbelkada  still same error after adding just setattr(model, 'model_parallel', True)

**Comment by younesbelkada** [comment] 2023-04-03 14:11
Hi @djaym7 @Shreyans92 
I managed to reproduce, https://github.com/huggingface/transformers/pull/22532 and another PR that I will share soon will fix these bugs

**Comment by Shreyans92** [comment] 2023-04-04 15:47
@younesbelkada thanks for the fix. I tried running the same and have one observation. When i am running the flan-t5-xxl 8 bit finetuning on g5.8x.large it is showing 27hrs to complete for an epoch but when i am moving to g5.12x.large it shows 35 hrs to complete the 1 epoch on the same dataset. I thought multi-gpu training will be faster. Is this expected?

**Comment by younesbelkada** [comment] 2023-04-04 15:48
Hi @Shreyans92 
I think it's because CPU offloading might be enabled for some reason, could you try to print `model.hf_device_map` ?

**Comment by Shreyans92** [comment] 2023-04-04 16:02
Here is the device_map:

{'shared': 0, 'decoder.embed_tokens': 0, 'encoder.embed_tokens': 0,
'encoder.block.0': 0, 'encoder.block.1': 0, 'encoder.block.2': 0,
'encoder.block.3': 0, 'encoder.block.4': 0, 'encoder.block.5': 0,
'encoder.block.6': 0, 'encoder.block.7': 0, 'encoder.block.8': 0,
'encoder.block.9': 0, 'encoder.block.10': 0, 'encoder.block.11': 0,
'encoder.block.12': 1, 'encoder.block.13': 1, 'encoder.block.14': 1,
'encoder.block.15': 1, 'encoder.block.16': 1, 'encoder.block.17': 1,
'encoder.block.18': 1, 'encoder.block.19': 1, 'encoder.block.20': 1,
'encoder.block.21': 1, 'encoder.block.22': 1, 'encoder.block.23': 1,
'encoder.final_layer_norm': 1, 'encoder.dropout': 1, 'decoder.block.0': 1,
'decoder.block.1': 1, 'decoder.block.2': 2, 'decoder.block.3': 2,
'decoder.block.4': 2, 'decoder.block.5': 2, 'decoder.block.6': 2,
'decoder.block.7': 2, 'decoder.block.8': 2, 'decoder.block.9': 2,
'decoder.block.10': 2, 'decoder.block.11': 2, 'decoder.block.12': 2,
'decoder.block.13': 2, 'decoder.block.14': 3, 'decoder.block.15': 3,
'decoder.block.16': 3, 'decoder.block.17': 3, 'decoder.block.18': 3,
'decoder.block.19': 3, 'decoder.block.20': 3, 'decoder.block.21': 3,
'decoder.block.22': 3, 'decoder.block.23': 3, 'decoder.final_layer_norm':
3, 'decoder.dropout': 3, 'lm_head': 3}


Looks Like everything is on gpu only.

**Comment by pacman100** [comment] 2023-04-04 18:33
Hello @Shreyans92,

Multi-GPU in this case is a sort of model parallelism wherein different layers are on different GPUs, also called naive pipelining. In this case, only one GPU is doing the computation while others are idling, hence `naive`, this allows for fitting big models but at the cost of inefficiency. Hence, the communication overheads of copying data/activations across different devices and the fact that only one GPU is computing while others are idling, it is likely the cause of the slowness you are observing in comparison to the case when the entire model is on the single 24GB GPU. 

If you can fit the model on a single GPU, you can do Distributed Data Parallelism by having `device_map = {"":device}` where the device is the GPU number. That way, num_gpus*batch_size is processed simultaneously and all the GPUs are computing all the time. @younesbelkada can provide an example script I think as he has successfully got this working. This is how multi-gpu can accelerate training.

**Comment by taishiciR** [comment] 2023-04-08 11:43
> pacman100
@pacman100 ，hi~ I wonder if it possible to do naive pipelining across 2 or more nodes (multi-host)

**Closed** 2023-05-12 15:03 UTC
Labels: solved

**Comment by junshipeng** [comment] 2023-05-18 03:14
whisper:ValueError: You can't train a model that has been loaded in 8-bit precision on multiple 
devices
