### ISSUE TITLE
PeftModel error with forward()

### ISSUE THREAD

**Issue by lqf0624** [huggingface/peft#1424] opened 2024-02-01 03:11 UTC
### System Info

peft = 0.7.1,accelerate=0.26.1,transformers=4.30.1
 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I'm applying LoRA in gpt-2. Addtionally, there are several layers added. My general model is like this:
```python
self.padding_patch_layer = nn.ReplicationPad1d((0,self.stride))
self.llm = GPT2Model.from_pretrained(self.model_dir,output_attentions=True, output_hidden_states=True)
self.llm.h = self.llm.h[:configs.layers]
self.in_layer = nn.Linear(configs.patch_size, configs.d_model)
        
self.out_layer = nn.Linear(configs.d_model * self.patch_num, configs.pred_len)
``` 
And I loaded LoRAConfig in this way:
```python
peft_config = LoraConfig(
                        task_type=TaskType.CAUSAL_LM,
                        target_modules=module_dict[model_type],
                        inference_mode=False,
                        r=1,
                        lora_alpha=32,
                        lora_dropout=0.1,
                    )
self.llm = get_peft_model(self.llm, peft_config)
print("Model Type: {}".format(type(self.llm)))
self.llm.print_trainable_parameters()
``` 
In forward() function, i tried to get the output of lora fine-tuned model, but get an error.
Here is the forward() function:
```python
def forward(self,x,itr):
        B , L , M = x.shape
        x,_ = self.norm_layer(x,mode="forward")
        x = rearrange(x,'b l m -> b m l')
        
        x = self.padding_patch_layer(x)
        x = x.unfold(dimension=-1, size=self.patch_size, step=self.stride)
        
        x = rearrange(x, 'b m n p -> (b m) n p')
        outputs = self.in_layer(x)
        
        
        outputs = self.llm(inputs_embeds=outputs).last_hidden_state
        outputs = self.out_layer(outputs.reshape(B*M,-1))
        outputs = rearrange(outputs, '(b m) l -> b l m',b=B)
        outputs = self.norm_layer(outputs,mode="inverse")
        return outputs
``` 
And here is the error:
```
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    outputs = model(batch_x,ii)
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/project/TS-lqf/LLaMA.py", line 108, in forward
    outputs = self.llm(inputs_embeds=outputs).last_hidden_state
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/peft/peft_model.py", line 1073, in forward
    return self.base_model(
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/lqf_TimesNet/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 103, in forward
    return self.model.forward(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'labels'

```

### Expected behavior

Cloud anyone tell me the correct way to get the output of PeftModel or how to fine-tune this structure of model in LoRA??

**Comment by BenjaminBossan** [comment] 2024-02-05 13:08
There is a lot of custom stuff going on here, which makes it hard to pinpoint the issue, much less to reproduce it. As a debugging step, could you confirm that the error vanishes if `self.llm` is just a standard GPT2, i.e. not using PEFT?

As a side note, using rank of 1 (`r=1`) is quite unusual. Although I don't think it's the source of the error, you probably want to choose a higher rank.

**Comment by lqf0624** [comment] 2024-02-05 13:32
> There is a lot of custom stuff going on here, which makes it hard to pinpoint the issue, much less to reproduce it. As a debugging step, could you confirm that the error vanishes if `self.llm` is just a standard GPT2, i.e. not using PEFT?
> 
> As a side note, using rank of 1 (`r=1`) is quite unusual. Although I don't think it's the source of the error, you probably want to choose a higher rank.

Yes,the bug vanished without using PEFT

**Comment by BenjaminBossan** [comment] 2024-02-06 09:15
Hmm, this is really hard to debug without a complete reproducer.

I tried to isolate the critical part of your code and it worked, so I'm not sure why your code fails:

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model
import torch

inputs_embeds = torch.rand((10, 20, 768))
llm = AutoModelForCausalLM.from_pretrained("gpt2")
# adding this line still works:
# llm.transformer.h = llm.transformer.h[:6]
llm(inputs_embeds=inputs_embeds)  # works

config = LoraConfig(task_type="CAUSAL_LM", r=16, init_lora_weights=False)
peft_model = get_peft_model(llm, config)
peft_model(inputs_embeds=inputs_embeds)  # works
```

**Comment by lqf0624** [comment] 2024-02-19 13:03
> Hmm, this is really hard to debug without a complete reproducer.
> 
> I tried to isolate the critical part of your code and it worked, so I'm not sure why your code fails:
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from peft import LoraConfig, get_peft_model
> import torch
> 
> inputs_embeds = torch.rand((10, 20, 768))
> llm = AutoModelForCausalLM.from_pretrained("gpt2")
> # adding this line still works:
> # llm.transformer.h = llm.transformer.h[:6]
> llm(inputs_embeds=inputs_embeds)  # works
> 
> config = LoraConfig(task_type="CAUSAL_LM", r=16, init_lora_weights=False)
> peft_model = get_peft_model(llm, config)
> peft_model(inputs_embeds=inputs_embeds)  # works
> ```

I apply LLaMA-2 like this:
```python
self.llm= LlamaModel.from_pretrained(self.model_dir,output_attentions=True, output_hidden_states=True)
peft_config = LoraConfig(
                         task_type=TaskType.CAUSAL_LM,
                         target_modules=module_dict[model_type],
                         inference_mode=False,
                         r=1,
                         lora_alpha=32,
                         lora_dropout=0.1,
                     )
                 self.llm = get_peft_model(self.llm, peft_config)

```

**Comment by BenjaminBossan** [comment] 2024-02-20 10:25
I still could not reproduce using this code (using a tiny llama2 for memory reasons):

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model
import torch

llm = AutoModelForCausalLM.from_pretrained("stas/tiny-random-llama-2", output_attentions=True, output_hidden_states=True)
# adding this line still works:
# llm.model.layers = llm.model.layers[:1]
inputs_embeds = torch.rand((10, 20, 16))
llm(inputs_embeds=inputs_embeds)  # works

config = LoraConfig(task_type="CAUSAL_LM", r=1, init_lora_weights=False, inference_mode=False, lora_alpha=32, lora_dropout=0.1)
peft_model = get_peft_model(llm, config)
peft_model(inputs_embeds=inputs_embeds)  # works
```

Could you please check if this runs successfully using your actual Llama2 model that you load from `self.model_dir`? If this works but your code still fails, there must be some difference still somewhere that causes it. Could you also try installing the latest versions of PEFT, accelerate, and transformers and check if that makes a difference?

**Comment by lqf0624** [comment] 2024-02-21 06:35
> I still could not reproduce using this code (using a tiny llama2 for memory reasons):
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from peft import LoraConfig, get_peft_model
> import torch
> 
> llm = AutoModelForCausalLM.from_pretrained("stas/tiny-random-llama-2", output_attentions=True, output_hidden_states=True)
> # adding this line still works:
> # llm.model.layers = llm.model.layers[:1]
> inputs_embeds = torch.rand((10, 20, 16))
> llm(inputs_embeds=inputs_embeds)  # works
> 
> config = LoraConfig(task_type="CAUSAL_LM", r=1, init_lora_weights=False, inference_mode=False, lora_alpha=32, lora_dropout=0.1)
> peft_model = get_peft_model(llm, config)
> peft_model(inputs_embeds=inputs_embeds)  # works
> ```
> 
> Could you please check if this runs successfully using your actual Llama2 model that you load from `self.model_dir`? If this works but your code still fails, there must be some difference still somewhere that causes it. Could you also try installing the latest versions of PEFT, accelerate, and transformers and check if that makes a difference?

I located the bug. It works when loading models with the function AutoModelForCausalLM. I replaced the loading function and the bug disappear. Also, I tried to replace the function to GPT2Model or LlamaModel in the code you gave above, the bug will be reproduced
So  grateful for your help!

**Comment by BenjaminBossan** [comment] 2024-02-21 10:45
Indeed, I could reproduce the error when using `LlamaModel`. It appears that using `LlamaModel.from_pretrained` does not load a `LlamaForCausalLM` but a `LlamaModel` instead, which does not accept the `label` argument. I'm not quite sure if this is expected or not, but since we have a solution, I think we can close the issue. Thanks for your patience.

**Closed by BenjaminBossan** 2024-02-21 10:45 UTC
