### ISSUE TITLE
AttributeError: 'PromptEncoder' object has no attribute 'mlp_head'

### ISSUE THREAD

**Issue by linguoqi** [huggingface/peft#1508] opened 2024-02-25 15:57 UTC
### System Info

python=3.10

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

#inference code
![image](https://github.com/huggingface/peft/assets/157370038/f45e33db-b050-49ee-b336-069b9eca260b)

train code
![image](https://github.com/huggingface/peft/assets/157370038/756d3952-ec88-489e-b5ed-d4977ff7bc02)

### Expected behavior

Is this error indicating that there's a problem with the configuration of my training or inference code?

**Comment by BenjaminBossan** [comment] 2024-02-26 09:44
This is a duplicate of #1500, right? If so, please close this issue.

**Closed** 2024-02-26 10:36 UTC
