### ISSUE TITLE
Implementing GLora

### ISSUE THREAD

**Issue by aravindhv10** [huggingface/peft#1510] opened 2024-02-26 16:16 UTC
### Feature request

Implementing GLORA in PEFT as a superset of LORA, reference:

https://arxiv.org/abs/2306.07967

### Motivation

This is a superset of regular LORA and performs better in some circumstances.

### Your contribution

I can help with implementation if given guidance.

**Comment by BenjaminBossan** [comment] 2024-02-26 16:38
Duplicate of #780. Do you have experience with GLoRA, did it work well for your use cases?

Also, note that there is a PEFT fork that contains a [GLoRA implementation](https://github.com/Arnav0400/peft/blob/0bcbe4549b54dbcc82c9354e7ba00b386a47b3eb/src/peft/tuners/glora.py) but it the fork is a bit out of date by now. Maybe you could still try to give it a go and see if it leads to improvements on your use cases.

**Comment by aravindhv10** [comment] 2024-02-27 06:33
I had used GLora with mixed results in Kohya SS SDXL dreambooth scripts. The results are mostly qualitative and some models were better than Lora. Thanks for the pointers! will have a look.

**Closed** 2024-04-06 15:03 UTC
